AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  This function retrieves the fulfillfed intent's conclusion statement using the
  Boto3 client before invoking the Indie fulfillment web service
Resources:
  lexInvokeIndieWebhook:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lexInvokeIndieWebhook.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: >-
        This function retrieves the fulfillfed intent's conclusion statement using the
        Boto3 client before invoking the Indie fulfillment web service
      MemorySize: 128
      Timeout: 10
      Role: >-
        <add role here>
      Layers:
        - 'arn:aws:lambda:us-east-1:668099181075:layer:AWSLambda-Python-AWS-SDK:4'
